// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   /**
    * public static final class DriveConstants {
    *   public static final int kLeftMotor1Port = 0;
    *   public static final int kLeftMotor2Port = 1;
    *   public static final int kRightMotor1Port = 2;
    *   public static final int kRightMotor2Port = 3; 
    * }
    */ 
    public static final double SCurveInnerIntakeManualForwardSpeed = 0.5;
    public static final double SCurveInnerIntakeManualBackwardSpeed = -0.5;

    public static final double SCurveSCurveManualForwardSpeed = 0.75*.75;
    public static final double SCurveSCurveManualBackwardSpeed = -0.75*.75;

    public static final double SCurveSCurveAutoForwardSpeed = 1*.75;
    public static final double SCurveIntakeAutoForwardSpeed = .625;//.375

    public static final double ShooterGearRatio = 34.0/42.0;
    public static final double ShooterFarShot = 2767;
    public static final double ShooterCloseShot = 2100;
    public static final double ShooterLowShot = 1800;
    public static final double ShooterFudgeFactor = 3.375;

    public static final double IntakeForwardSpeed = 0.25*1.5;
    public static final double IntakeReverseSpeed = -0.25;

    public static final double JoyStick1DeadBandWidthX = 0.05;
    public static final double JoyStick1DeadBandWidthY = 0.05;
    public static final double JoyStick1DeadBandWidthR = 0.05;

    public static final double DrivetrainFieldOrientedOffsetAngle = 180;
}